version: '3.1'

services:
  fluentd-logger:
    container_name: fluentd-logger
    image: loopchain-fluentd:latest
    volumes:
      - ${LOG_PATH}:/fluentd/log
    ports:
      - 24224:24224
    networks:
      - loopchain
  radio_station:
    container_name: radio_station
    image: looprs:${TAG}
    env_file: ./env_${TAG}.list
    depends_on:
      - fluentd-logger
    ports:
      - 7102:7102
      - 9002:9002
    command: python3 radiostation.py
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    networks:
      - loopchain
  peer0:
    container_name: peer0
    image: looppeer:${TAG}
    env_file: ./env_${TAG}.list
    depends_on:
      - fluentd-logger
      - radio_station
    links:
      - radio_station
    ports:
      - 7100:7100
      - 9000:9000
    command: python3 peer.py -c ${DEPLOY_SCORE} -r radio_station -p 7100
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    networks:
      - loopchain
  peer1:
    container_name: peer1
    image: looppeer:${TAG}
    env_file: ./env_${TAG}.list
    depends_on:
      - fluentd-logger
      - radio_station
    links:
      - radio_station
    ports:
      - 7200:7200
      - 9100:9100
    command:  python3 peer.py -c ${DEPLOY_SCORE} -r radio_station -p 7200
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    networks:
      - loopchain
  peer2:
    container_name: peer2
    image: looppeer:${TAG}
    env_file: ./env_${TAG}.list
    depends_on:
      - fluentd-logger
      - radio_station
    links:
      - radio_station
    ports:
      - 7300:7300
      - 9200:9200
    command: python3 peer.py -c ${DEPLOY_SCORE} -r radio_station -p 7300
    networks:
      - loopchain
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
networks:
    loopchain:
        external: true
